import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import {
  CHASSIS_LABELS,
  CHASSIS_NOTES,
  CHASSIS_ORDER,
  MARKERS_BY_CHASSIS,
  PROMOTERS_BY_CHASSIS,
  SCREENABLE_POOL,
  TARGET_CLASSES,
  TARGET_ORGANISMS,
  TOPOLOGIES,
  defaultMarkerId,
  defaultPromoterId,
  getOrganism,
  lengthForOrganism,
  suggestedPanelFor,
  type CassetteTopology,
  type DeliveryChassis,
  type TargetClass,
} from "../data/rnaDesignCatalog";
import {
  buildCassette,
  buildFasta,
  buildGenBank,
  buildPrimers,
  discoverTargets,
  downloadText,
  getFold,
  primersToCsv,
  removeGoldenGateSite,
  screenOffTargets,
  tileSirnas,
  type CassetteDesign,
  type FoldingProfile,
  type SirnaCandidate,
} from "../utils/rnaDesign";
import "./NectarDesigner.css";

/* NectarDesigner, as a figure you step through.
 *
 * WHAT THIS IS. The dry lab built a standalone front end for the RNA design
 * pipeline. This is that work brought onto the wiki: the same seven decisions,
 * in the same order, rebuilt in the wiki's own type, palette and comb rather
 * than carried over as a second website with its own dark theme. A judge
 * should be able to read the argument without leaving /software.
 *
 * ONE STEP AT A TIME. The rail across the top switches between the seven; only
 * the chosen one is drawn. Unlike the original, no step is ever locked: every
 * stage is computed on every render whatever you are looking at, so a reader
 * who wants to see the screen can go straight to it. What carries the argument
 * is that the stages CONSTRAIN each other. Change the pest and the duplex
 * length changes, tighten the threshold and windows die, kill enough of them
 * and the construct has less to carry. Step back and forth after changing a
 * control and that chain is visible.
 *
 * WHAT IT IS NOT. Every number, sequence, fold and off-target hit here is
 * generated by src/utils/rnaDesign.ts from a seeded generator. It is a working
 * model of the pipeline's SHAPE, not the pipeline, and nothing it prints is a
 * biological prediction. The real ranking code's weights, thresholds and
 * training corpus are held back pending the IP position.
 *
 * THE FOLD IS NOT A ViennaRNA OUTPUT. The real pipeline folds with ViennaRNA
 * 2.7.2, Turner 2004, 37 C, partition function (see the DBTL cycles). The
 * structure that settles in step 4 below is built by a grammar that emits
 * plausible stems and loops, because shipping a folding engine into a wiki
 * bundle with a 5 MB ceiling is not on. The LAYOUT is real physics: a spring
 * and repulsion simulation actually run in your browser, which is why it
 * settles rather than appearing. Do not let anyone read it as a prediction.
 *
 * MOTION, AND WHY IT IS BACK. The house design rules allow motion that aids
 * understanding and ban it as decoration. Four things move here and each one
 * shows a process rather than dressing it: the fold settles, so you see stems
 * pull their partners together; the guide strand melts its site open and then
 * docks, which is the energy cost in step 3 happening; the screen sweeps one
 * species at a time, so rejection is something you watch rather than a table
 * that was always red; and switching step moves the panel. Everything obeys
 * prefers-reduced-motion, and the toolbar carries a switch as well, because a
 * reader may want it still on a machine that never set the preference.
 *
 * NO NEW DEPENDENCIES. The original ran on Tailwind, framer-motion, d3 and
 * zustand. None is in this wiki and the build has a 5 MB ceiling, so the force
 * simulation, the geometry and the easing are hand-rolled, and the state is
 * useState. Brand tokens only, from src/styles/brand.css.
 */

/* ---------- geometry ---------- */

/* A flat-top hexagon, normalised. In a box of width w and height (sqrt3/2)w
 * the six corners always land on these fractions, so ONE clip path in
 * objectBoundingBox units fits every cell at every size, and a cap is just a
 * rectangle clipped by it. Flat-top rather than pointy-top because the cap has
 * to come down onto a flat edge the way wax does. */
const HEX_CLIP = "0.25,0 0.75,0 1,0.5 0.75,1 0.25,1 0,0.5";
const HEX_RATIO = Math.sqrt(3) / 2;

/** Flat-top hexagon corner points for a w-wide box at (x, y). */
function hexPoints(x: number, y: number, w: number): string {
  const h = w * HEX_RATIO;
  return [
    [x + w * 0.25, y],
    [x + w * 0.75, y],
    [x + w, y + h / 2],
    [x + w * 0.75, y + h],
    [x + w * 0.25, y + h],
    [x, y + h / 2],
  ]
    .map(([px, py]) => `${px.toFixed(2)},${py.toFixed(2)}`)
    .join(" ");
}

/* ---------- motion ---------- */

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    window.matchMedia?.("(prefers-reduced-motion: reduce)").matches === true
  );
}

/* ---------- the steps ---------- */

const STEPS = [
  {
    n: 1,
    label: "Target",
    title: "Target intake",
    decides:
      "Which organism the design is aimed at, and what kind of gene it should silence.",
  },
  {
    n: 2,
    label: "Configure",
    title: "Run configuration",
    decides:
      "How wide to cast, how strict to be about off-target matches, and which species must not be affected.",
  },
  {
    n: 3,
    label: "Rank genes",
    title: "Ranking the candidate genes",
    decides: "Which gene is worth designing against at all.",
  },
  {
    n: 4,
    label: "Fold",
    title: "Accessibility, and the windows inside the gene",
    decides: "Which stretch of that gene the silencing machinery can reach.",
  },
  {
    n: 5,
    label: "Screen",
    title: "Screening against everything else",
    decides: "Which of those windows are safe enough to keep.",
  },
  {
    n: 6,
    label: "Build",
    title: "An expression-ready construct",
    decides:
      "How the surviving windows are assembled into something the wet lab can order.",
  },
  {
    n: 7,
    label: "Export",
    title: "What comes out",
    decides: "The files the wet lab would actually work from.",
  },
] as const;

/* ---------- small shared pieces ---------- */

/** A control group with a real label and an explanation that is always
 * visible, because nothing on this wiki may exist only behind a pointer. */
function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: ReactNode;
}) {
  return (
    <div className="nd-field">
      <span className="nd-field-label">{label}</span>
      {children}
      {hint ? <p className="nd-field-hint">{hint}</p> : null}
    </div>
  );
}

/* ---------- the accessibility comb ---------- */

const COMB_BINS = 44;
const COMB_CELL_W = 20;
const COMB_GAP = 2;

/* THE TWO FIGURES SHOW DIFFERENT THINGS, which is how the original divided
 * the work and why neither has to compromise.
 *
 * The comb is the WHOLE transcript, binned, with a marker showing the stretch
 * the fold is drawing. At a couple of thousand nucleotides across 44 cells it
 * cannot resolve an individual stem, and it is not trying to: its job is
 * "here is all of it, and here is where you are looking".
 *
 * The fold draws only a WINDOW, because a folded structure of 2,700
 * nucleotides is a hairball nobody can read. These are the original's own
 * numbers: it opened on the first 150 and narrowed to the selected window
 * plus 40 either side, which for a 24-mer is 104 nucleotides. */
const FOLD_PAD = 40;
const FOLD_DEFAULT_SPAN = 150;

/** A stretch of the transcript, binned, with occlusion drawn as wax capping
 * each cell. The stretch follows the selected window, because the question
 * this figure answers is whether THAT window sits somewhere reachable. */
function AccessibilityComb({
  unpaired,
  from,
  to,
  markedFrom,
  markedTo,
  clipId,
}: {
  unpaired: number[];
  from: number;
  to: number;
  markedFrom: number | null;
  markedTo: number | null;
  clipId: string;
}) {
  const bins = useMemo(() => {
    const size = Math.max(1, Math.ceil((to - from) / COMB_BINS));
    const out: Array<{ start: number; end: number; open: number }> = [];
    for (let start = from; start < to; start += size) {
      const end = Math.min(to, start + size);
      let sum = 0;
      for (let i = start; i < end; i++) sum += unpaired[i] ?? 0;
      out.push({ start, end, open: sum / (end - start) });
    }
    return out;
  }, [unpaired, from, to]);

  const cellH = COMB_CELL_W * HEX_RATIO;
  const width = bins.length * (COMB_CELL_W + COMB_GAP) - COMB_GAP;

  return (
    <svg
      viewBox={`0 0 ${width} ${cellH}`}
      className="nd-comb"
      role="img"
      aria-label={`Accessibility across nucleotides ${from + 1} to ${to}. An open cell is a stretch the fold leaves available; a cell capped in wax is occluded by the transcript's own secondary structure.`}
    >
      <defs>
        <clipPath id={clipId} clipPathUnits="objectBoundingBox">
          <polygon points={HEX_CLIP} />
        </clipPath>
      </defs>
      {bins.map((bin, i) => {
        const x = i * (COMB_CELL_W + COMB_GAP);
        const capped = (1 - bin.open) * cellH;
        const marked =
          markedFrom !== null &&
          markedTo !== null &&
          bin.end > markedFrom &&
          bin.start < markedTo;
        return (
          <g key={bin.start}>
            <g clipPath={`url(#${clipId})`}>
              <rect
                x={x}
                y={0}
                width={COMB_CELL_W}
                height={cellH}
                className="nd-comb-open"
              />
              {capped > 0.4 ? (
                <rect
                  x={x}
                  y={0}
                  width={COMB_CELL_W}
                  height={capped}
                  className="nd-comb-cap"
                />
              ) : null}
            </g>
            <polygon
              points={hexPoints(x, 0, COMB_CELL_W)}
              className={marked ? "nd-comb-edge is-marked" : "nd-comb-edge"}
            >
              <title>
                {`Nucleotides ${bin.start + 1} to ${bin.end}: ${Math.round(bin.open * 100)}% accessible`}
              </title>
            </polygon>
          </g>
        );
      })}
    </svg>
  );
}

/* ---------- the folding view ---------- */

/* The structure, laid out by a spring simulation that actually runs.
 *
 * The backbone is a chain of springs, every base pair is one more spring
 * across the chain, and every nucleotide pushes its neighbours away. Released
 * from a straight line, that is enough to make stems zip together and loops
 * bulge out, which is why the thing settles into recognisable shapes instead
 * of a hairball. It is the same idea as a force-directed graph layout; it is
 * hand-rolled because d3-force is not a dependency of this wiki and a 5 MB
 * build ceiling is not the place to add one.
 *
 * THE LAYOUT IS REAL, THE STRUCTURE IS NOT. Which bases pair with which comes
 * from the generated dot-bracket in src/utils/rnaDesign.ts, not from folding
 * anything. The real pipeline uses ViennaRNA 2.7.2. Nothing that settles here
 * is a prediction about a real transcript.
 *
 * Positions live in one Float64Array and are written straight onto the DOM in
 * the animation frame. Putting 176 nucleotides through React state sixty times
 * a second would drop frames for no benefit, since nothing about the tree
 * changes as they move, only their transforms. */

/* ---------- the folding panel's own palette ---------- */

/* THE ONE PLACE ON THIS WIKI THAT DOES NOT WEAR THE BRAND PALETTE, and
 * deliberately. These are the dry lab's own values, carried over unchanged
 * from the standalone tool (modelleing-frontend/src/lib/theme.ts), because
 * the folding view is an instrument the team already designed and because
 * four nucleotide identities genuinely need four hues. Everything else in
 * this component stays honey and wax; this panel is a dark inset, the way a
 * gel photograph or a micrograph would be.
 *
 * Checked with the dataviz validator against this panel's own navy rather
 * than assumed: separation under simulated protanopia and deuteranopia, the
 * normal-vision floor and 3:1 contrast all pass. The one check it misses is
 * the lightness-uniformity band, and that is the intended look rather than a
 * defect, since bright bases on a dark ground is the whole design. */
const FOLD_NAVY = "#16265C";
const FOLD_NAVY_DEEP = "#101C47";
const FOLD_YELLOW = "#F2C94C";
const FOLD_WAX = "#BFA97C";
const FOLD_PAPER = "#FFFFFF";

const BASE_COLOURS: Record<string, string> = {
  A: "#3EC6E0",
  U: "#EF5DA8",
  T: "#EF5DA8",
  G: "#57D68D",
  C: "#9B7BF0",
};

/** Navy-tint when occluded through to brand yellow when open. The original's
 * ramp, and the one place yellow carries a value rather than meaning chrome. */
function accessibilityColour(t: number): string {
  const c = Math.min(1, Math.max(0, t));
  const from = [0x2e, 0x3f, 0x73];
  const to = [0xf2, 0xc9, 0x4c];
  const mix = from.map((f, i) => Math.round(f + (to[i] - f) * c));
  return `rgb(${mix[0]}, ${mix[1]}, ${mix[2]})`;
}

/* Tuned by running the simulation headlessly and measuring, not by eye. At
 * these numbers a 176 nt window settles into roughly 390 x 292 of the box
 * below, base pairs come to rest within half a unit of their spring's rest
 * length, no two unpaired nucleotides end up closer than the cell is wide, and
 * nothing is left pinned against an edge. Checked to hold for a sparse fold of
 * 11 pairs and a dense one of 54, so it does not need retuning per transcript. */
const FOLD_W = 700;
const FOLD_H = 520;
/** 12, as the original drew them. Big enough that a base's colour reads at a
 * glance and that the wax cap over it is a visible fraction rather than a
 * hairline. */
const FOLD_CELL = 12;
const FOLD_TICKS = 460;
const BACKBONE_REST = 28;
const PAIR_REST = 15;
const REPEL_CUTOFF = 56;
const REPEL_STRENGTH = 0.029;
const CENTRING = 0.0007;

/** One spring between two nodes, pulling toward `rest`. */
function spring(
  p: Float64Array,
  a: number,
  b: number,
  rest: number,
  k: number,
): void {
  const dx = p[b * 4] - p[a * 4];
  const dy = p[b * 4 + 1] - p[a * 4 + 1];
  const d = Math.hypot(dx, dy) || 0.001;
  const f = ((d - rest) * k) / 2;
  const ux = (dx / d) * f;
  const uy = (dy / d) * f;
  p[a * 4 + 2] += ux;
  p[a * 4 + 3] += uy;
  p[b * 4 + 2] -= ux;
  p[b * 4 + 3] -= uy;
}

function foldTick(
  p: Float64Array,
  n: number,
  pairs: Array<[number, number]>,
  bonded: Set<number>,
): void {
  for (let i = 0; i < n - 1; i++) spring(p, i, i + 1, BACKBONE_REST, 0.3);
  for (const [a, b] of pairs) spring(p, a, b, PAIR_REST, 0.28);

  /* Short-range repulsion, so the chain cannot fold through itself.
   *
   * Base-paired partners are skipped. They already have a spring holding them
   * at the pair rest length, and letting them repel as well means the two
   * forces fight: measured, that left every stem sitting about 40% wider than
   * its rest length, so the rungs drew long and the stems never looked closed.
   * Skipping them brings pair distance back to within half a unit of rest. */
  const cut2 = REPEL_CUTOFF * REPEL_CUTOFF;
  for (let i = 0; i < n; i++) {
    for (let j = i + 2; j < n; j++) {
      if (bonded.has(i * 4096 + j)) continue;
      const dx = p[j * 4] - p[i * 4];
      const dy = p[j * 4 + 1] - p[i * 4 + 1];
      const d2 = dx * dx + dy * dy;
      if (d2 > cut2 || d2 === 0) continue;
      const d = Math.sqrt(d2);
      const f = (REPEL_CUTOFF - d) * REPEL_STRENGTH;
      const ux = (dx / d) * f;
      const uy = (dy / d) * f;
      p[i * 4 + 2] -= ux;
      p[i * 4 + 3] -= uy;
      p[j * 4 + 2] += ux;
      p[j * 4 + 3] += uy;
    }
  }

  const cx = FOLD_W / 2;
  const cy = FOLD_H / 2;
  for (let i = 0; i < n; i++) {
    p[i * 4 + 2] += (cx - p[i * 4]) * CENTRING;
    p[i * 4 + 3] += (cy - p[i * 4 + 1]) * CENTRING;
    p[i * 4 + 2] *= 0.85;
    p[i * 4 + 3] *= 0.85;
    p[i * 4] = Math.max(12, Math.min(FOLD_W - 12, p[i * 4] + p[i * 4 + 2]));
    p[i * 4 + 1] = Math.max(
      12,
      Math.min(FOLD_H - 12, p[i * 4 + 1] + p[i * 4 + 3]),
    );
  }
}

function FoldedStructure({
  profile,
  from,
  to,
  markFrom,
  markTo,
  markLabel,
  colourMode,
  motion,
  clipId,
  glowId,
  runKey,
}: {
  profile: FoldingProfile;
  from: number;
  to: number;
  markFrom: number | null;
  markTo: number | null;
  markLabel?: string;
  colourMode: "base" | "accessibility";
  motion: boolean;
  clipId: string;
  glowId: string;
  /** Changing this restarts the simulation from a straight line. */
  runKey: string;
}) {
  const n = to - from;
  const cells = useRef<Array<SVGGElement | null>>([]);
  /** The wax caps, kept separately because their height is animated as the
   * structure settles rather than being fixed at first paint. */
  const caps = useRef<Array<SVGRectElement | null>>([]);
  const backbone = useRef<SVGPathElement>(null);
  const rungs = useRef<SVGPathElement>(null);
  const leader = useRef<SVGLineElement>(null);
  const leaderText = useRef<SVGTextElement>(null);
  const [running, setRunning] = useState(motion);

  const pairs = useMemo(() => {
    const out: Array<[number, number]> = [];
    for (const [i, j] of profile.pairs) {
      if (i >= from && j < to) out.push([i - from, j - from]);
    }
    return out;
  }, [profile.pairs, from, to]);

  /** The same pairs as a flat lookup, so the repulsion loop can skip bonded
   * partners without searching the list on every one of its n-squared steps. */
  const bonded = useMemo(() => {
    const set = new Set<number>();
    for (const [a, b] of pairs) set.add(Math.min(a, b) * 4096 + Math.max(a, b));
    return set;
  }, [pairs]);

  useEffect(() => {
    if (n <= 1) return;
    const p = new Float64Array(n * 4);
    for (let i = 0; i < n; i++) {
      p[i * 4] = 24 + (i / (n - 1)) * (FOLD_W - 48);
      // A hair off the axis, or the first tick has no direction to push in.
      p[i * 4 + 1] = FOLD_H / 2 + (i % 2 === 0 ? -0.4 : 0.4);
    }

    const cellH = FOLD_CELL * HEX_RATIO;
    const halfH = cellH / 2;

    /* `settle` runs 0 to 1 as the structure comes to rest, and the wax caps
     * close over the occluded bases in step with it. The original did the
     * same: the chain finds its shape and the occlusion seals in behind it,
     * rather than the whole picture arriving at once. */
    const draw = (settle: number) => {
      let bb = "";
      for (let i = 0; i < n; i++) {
        bb += `${i === 0 ? "M" : "L"}${p[i * 4].toFixed(1)},${p[i * 4 + 1].toFixed(1)}`;
      }
      backbone.current?.setAttribute("d", bb);

      let rr = "";
      for (const [a, b] of pairs) {
        rr += `M${p[a * 4].toFixed(1)},${p[a * 4 + 1].toFixed(1)}L${p[b * 4].toFixed(1)},${p[b * 4 + 1].toFixed(1)}`;
      }
      rungs.current?.setAttribute("d", rr);

      let sx = 0;
      let sy = 0;
      let marked = 0;
      for (let i = 0; i < n; i++) {
        const x = p[i * 4];
        const y = p[i * 4 + 1];
        cells.current[i]?.setAttribute(
          "transform",
          `translate(${(x - FOLD_CELL / 2).toFixed(1)},${(y - halfH).toFixed(1)})`,
        );
        const open = profile.unpairedProbability[from + i] ?? 0.5;
        caps.current[i]?.setAttribute(
          "height",
          ((1 - open) * cellH * settle).toFixed(2),
        );
        if (
          markFrom !== null &&
          markTo !== null &&
          from + i >= markFrom &&
          from + i < markTo
        ) {
          sx += x;
          sy += y;
          marked += 1;
        }
      }

      // The leader from the label down onto the selected window.
      if (marked > 0 && leader.current && leaderText.current) {
        const cx = sx / marked;
        const cy = sy / marked;
        const top = Math.max(16, cy - 40);
        leader.current.setAttribute("x1", cx.toFixed(1));
        leader.current.setAttribute("x2", cx.toFixed(1));
        leader.current.setAttribute("y1", top.toFixed(1));
        leader.current.setAttribute("y2", cy.toFixed(1));
        leaderText.current.setAttribute("x", cx.toFixed(1));
        leaderText.current.setAttribute("y", Math.max(11, cy - 46).toFixed(1));
      }
    };

    if (!motion) {
      for (let t = 0; t < FOLD_TICKS; t++) foldTick(p, n, pairs, bonded);
      draw(1);
      setRunning(false);
      return;
    }

    setRunning(true);
    let frame = 0;
    let raf = 0;
    const frames = FOLD_TICKS / 2;
    const step = () => {
      // Two ticks a frame: one is a slow crawl at this damping, four overshoots
      // and the structure snaps rather than settles.
      foldTick(p, n, pairs, bonded);
      foldTick(p, n, pairs, bonded);
      frame++;
      draw(Math.min(1, frame / frames));
      if (frame < frames) {
        raf = requestAnimationFrame(step);
      } else {
        setRunning(false);
      }
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [n, pairs, bonded, motion, runKey, profile, from, markFrom, markTo]);

  return (
    <>
    <svg
      viewBox={`0 0 ${FOLD_W} ${FOLD_H}`}
      className="nd-fold"
      role="img"
      aria-label={`The predicted secondary structure of nucleotides ${from + 1} to ${to}, with ${pairs.length} base pairs drawn as rungs across the backbone. Accessibility of every position is also given in the table of windows below.`}
    >
      <defs>
        <clipPath id={clipId} clipPathUnits="objectBoundingBox">
          <polygon points={HEX_CLIP} />
        </clipPath>
        {/* The halo the original put behind the selected window. Applied to
            at most a couple of dozen cells, never to all of them. */}
        <filter id={glowId} x="-120%" y="-120%" width="340%" height="340%">
          <feDropShadow
            dx="0"
            dy="0"
            stdDeviation="2.4"
            floodColor={FOLD_YELLOW}
            floodOpacity="0.95"
          />
        </filter>
      </defs>

      <rect width={FOLD_W} height={FOLD_H} fill={FOLD_NAVY} />

      {/* Offset a whisker apart, as the original drew them, so the rungs read
          as crossing behind the chain rather than lying on it. */}
      <g transform="translate(-2,-2)">
        <path
          ref={backbone}
          d=""
          fill="none"
          stroke={FOLD_PAPER}
          strokeOpacity={0.35}
          strokeWidth={1.5}
          strokeLinejoin="round"
          strokeLinecap="round"
        />
      </g>
      <g transform="translate(2,2)">
        <path
          ref={rungs}
          d=""
          fill="none"
          stroke={FOLD_YELLOW}
          strokeOpacity={0.55}
          strokeWidth={1}
          strokeDasharray="2 2"
        />
      </g>

      {markLabel ? (
        <g>
          <line ref={leader} stroke={FOLD_YELLOW} strokeWidth={1} />
          <text
            ref={leaderText}
            textAnchor="middle"
            className="nd-fold-leader"
            fill={FOLD_YELLOW}
          >
            {markLabel}
          </text>
        </g>
      ) : null}

      {Array.from({ length: n }, (_, i) => {
        const base = (profile.sequence[from + i] ?? "A").toUpperCase();
        const open = profile.unpairedProbability[from + i] ?? 0.5;
        const marked =
          markFrom !== null &&
          markTo !== null &&
          from + i >= markFrom &&
          from + i < markTo;
        const fill =
          colourMode === "base"
            ? (BASE_COLOURS[base] ?? FOLD_NAVY_DEEP)
            : accessibilityColour(open);
        return (
          <g
            key={i}
            ref={(el) => {
              cells.current[i] = el;
            }}
            filter={marked ? `url(#${glowId})` : undefined}
          >
            <g clipPath={`url(#${clipId})`}>
              <rect width={FOLD_CELL} height={FOLD_CELL * HEX_RATIO} fill={fill} />
              {/* Height is written each frame as the structure settles. */}
              <rect
                ref={(el) => {
                  caps.current[i] = el;
                }}
                width={FOLD_CELL}
                height={0}
                fill={FOLD_WAX}
              />
            </g>
            <polygon
              points={hexPoints(0, 0, FOLD_CELL)}
              fill="none"
              stroke={marked ? FOLD_YELLOW : FOLD_NAVY_DEEP}
              strokeWidth={marked ? 1.2 : 0.6}
            >
              <title>
                {`${base} at position ${from + i + 1}, ${Math.round(open * 100)}% accessible`}
              </title>
            </polygon>
          </g>
        );
      })}
      </svg>
      {/* Only while it is moving, and the space is reserved either way so the
          figure does not jump when it stops. Set as HTML rather than as SVG
          text because text inside the viewBox scales with it. */}
      <p className="nd-fold-status" aria-live="polite">
        {running ? "Settling the structure" : ""}
      </p>
    </>
  );
}

/* ---------- the docking readout ---------- */

const DOCK_PAD = 3;

/** One candidate against its site: the bases either side, the antisense strand
 * that has to pair with them, and the energy the pairing costs and returns.
 *
 * The animation is the argument of step 3. An occluded site MELTS first, wax
 * lifting off the footprint, and only then does the guide slide in and its
 * bonds close one at a time. An already-open site skips the melt entirely.
 * Watching the first case take longer is what the cost-to-open number means. */
function DockingView({
  candidate,
  sequence,
  motion,
  clipId,
}: {
  candidate: SirnaCandidate;
  sequence: string;
  motion: boolean;
  clipId: string;
}) {
  const occluded = candidate.accessibility < 0.6;
  const [phase, setPhase] = useState<"melt" | "dock" | "done">(() =>
    !motion ? "done" : occluded ? "melt" : "dock",
  );

  useEffect(() => {
    if (!motion) {
      setPhase("done");
      return;
    }
    setPhase(occluded ? "melt" : "dock");
    const timers: Array<ReturnType<typeof setTimeout>> = [];
    const dockAt = occluded ? 1100 : 0;
    if (occluded) timers.push(setTimeout(() => setPhase("dock"), dockAt));
    timers.push(
      setTimeout(
        () => setPhase("done"),
        dockAt + 420 + candidate.length * 38 + 160,
      ),
    );
    return () => timers.forEach(clearTimeout);
  }, [candidate.id, candidate.length, occluded, motion]);

  const start = Math.max(0, candidate.position - DOCK_PAD);
  const end = Math.min(
    sequence.length,
    candidate.position + candidate.length + DOCK_PAD,
  );
  const target = sequence.slice(start, end).split("");
  const footprintFrom = candidate.position - start;
  const antisense = candidate.antisenseSeq.split("");
  const net = candidate.deltaGDuplex + candidate.deltaGOpen;

  const cellW = 22;
  const gap = 2;
  const cellH = cellW * HEX_RATIO;
  const pitch = cellW + gap;
  const width = target.length * pitch - gap;
  const rowTwo = cellH + 26;
  const height = rowTwo + cellH;
  const melting = phase === "melt";

  return (
    <div className="nd-dock" data-phase={phase}>
      <svg
        viewBox={`0 0 ${width} ${height}`}
        className="nd-dock-svg"
        role="img"
        aria-label={`The ${candidate.length} nucleotide window at position ${candidate.position}, sense strand ${candidate.senseSeq}, with the antisense guide ${candidate.antisenseSeq} paired beneath it.`}
      >
        <defs>
          <clipPath id={clipId} clipPathUnits="objectBoundingBox">
            <polygon points={HEX_CLIP} />
          </clipPath>
        </defs>

        {target.map((base, i) => {
          const x = i * pitch;
          const inFootprint =
            i >= footprintFrom && i < footprintFrom + candidate.length;
          const capped = inFootprint && melting ? cellH * 0.6 : 0;
          return (
            <g key={`t${i}`}>
              <g clipPath={`url(#${clipId})`}>
                <rect
                  x={x}
                  y={0}
                  width={cellW}
                  height={cellH}
                  className={
                    inFootprint ? "nd-dock-cell is-footprint" : "nd-dock-cell"
                  }
                />
                <rect
                  x={x}
                  y={0}
                  width={cellW}
                  height={capped}
                  className="nd-dock-melt"
                />
              </g>
              <text
                x={x + cellW / 2}
                y={cellH / 2}
                dominantBaseline="central"
                textAnchor="middle"
                className="nd-dock-base"
              >
                {base}
              </text>
            </g>
          );
        })}

        {/* Bonds close one at a time, drawn with a dash offset rather than a
            scale: an SVG line has no useful transform origin of its own, and
            this is the same mechanism the engineering comb's connector uses. */}
        <g className="nd-dock-bonds" data-on={phase !== "melt" ? "yes" : "no"}>
          {antisense.map((_, i) => {
            const x = (footprintFrom + i) * pitch + cellW / 2;
            return (
              <line
                key={`b${i}`}
                x1={x}
                x2={x}
                y1={cellH + 3}
                y2={rowTwo - 3}
                pathLength={1}
                className="nd-dock-bond"
                style={{ animationDelay: motion ? `${i * 38}ms` : "0ms" }}
              />
            );
          })}
        </g>

        {/* Two groups on purpose. The outer one carries the position as a
            transform attribute; the inner one is what the stylesheet animates.
            On one element a CSS transform would replace the attribute rather
            than compose with it, and the guide would fly off to the origin. */}
        <g transform={`translate(${footprintFrom * pitch}, ${rowTwo})`}>
          <g
            className="nd-dock-guide"
            data-on={phase !== "melt" ? "yes" : "no"}
          >
            {antisense.map((base, i) => (
              <g key={`a${i}`} transform={`translate(${i * pitch}, 0)`}>
                <g clipPath={`url(#${clipId})`}>
                  <rect
                    width={cellW}
                    height={cellH}
                    className="nd-dock-cell is-guide"
                  />
                </g>
                <text
                  x={cellW / 2}
                  y={cellH / 2}
                  dominantBaseline="central"
                  textAnchor="middle"
                  className="nd-dock-base"
                >
                  {base}
                </text>
              </g>
            ))}
          </g>
        </g>
      </svg>

      <p className="nd-dock-note">
        {occluded
          ? "This site sits inside a stem. The competing structure has to melt open before the guide can pair with it, and that cost is the first number below."
          : "This site is already open, so the guide pairs with it directly and there is no competing structure to displace."}
      </p>

      <dl className="nd-readouts">
        <div>
          <dt>Cost to open</dt>
          <dd>{candidate.deltaGOpen.toFixed(1)}</dd>
          <p>kcal/mol spent melting the local structure</p>
        </div>
        <div>
          <dt>Duplex formed</dt>
          <dd>{candidate.deltaGDuplex.toFixed(1)}</dd>
          <p>kcal/mol released by the guide pairing</p>
        </div>
        <div>
          <dt>Net</dt>
          <dd>{net.toFixed(1)}</dd>
          <p>kcal/mol overall, and more negative is better</p>
        </div>
      </dl>
    </div>
  );
}

/* ---------- the off-target matrix ---------- */

type CellState = "pass" | "caution" | "hit" | "unscreenable";

function cellState(
  longestMatch: number,
  isHit: boolean,
  unscreenable: boolean,
  threshold: number,
): CellState {
  if (unscreenable) return "unscreenable";
  if (isHit) return "hit";
  return longestMatch / threshold >= 0.7 ? "caution" : "pass";
}

const STATE_WORD: Record<CellState, string> = {
  pass: "clear",
  caution: "close to the threshold",
  hit: "rejected",
  unscreenable: "not screened",
};

/* Matrix geometry, in PIXELS. The matrix is drawn at its natural size and
 * never scaled up, because SVG text scales with the viewBox: a five-species
 * matrix stretched to fill the column would render its species labels several
 * times larger than the prose around it. It only ever shrinks, on a screen too
 * narrow to hold it.
 *
 * The left gutter holds a row number and the top band holds the species name
 * on a slant, so a long common name fits without absurdly wide columns. Rows
 * are numbered rather than labelled with their sequence: a 24 nt string is too
 * wide to be an axis label, so the number is the key and the table underneath
 * carries the same number against the full sequence. */
const MATRIX_LEFT = 34;
const MATRIX_TOP = 116;
const MATRIX_CELL = 32;
const MATRIX_COL = 36;
const MATRIX_ROW = 29;

/* ---------- the construct feature map ---------- */

/* Emphasis rather than a categorical palette. The insert is the thing the
 * seven steps produced, so it is the only honey on the bar; the backbone is
 * context and takes the wax. Six feature types would need six hues that hold
 * apart under colour-vision deficiency, and the brand palette does not have
 * them: the dataviz validator fails that set on both the normal-vision and the
 * CVD separation checks. Type therefore lives in the table below, where it is
 * exact, and the bar carries position, proportion and strand. */
function FeatureMap({ design }: { design: CassetteDesign }) {
  return (
    <figure className="nd-figure">
      <div
        className="nd-map"
        role="img"
        aria-label={`Linear map of a ${design.lengthBp} base pair construct with ${design.features.length} features. The full list is in the table below.`}
      >
        {design.features.map((feature) => {
          const share = ((feature.end - feature.start) / design.lengthBp) * 100;
          return (
            <div
              key={feature.id}
              className={
                feature.type === "insert" ? "nd-map-part is-insert" : "nd-map-part"
              }
              style={{ width: `${share}%` }}
              title={`${feature.name}, ${feature.start + 1} to ${feature.end}, ${feature.strand === 1 ? "forward" : "reverse"} strand`}
            >
              {share > 11 ? (
                <span className="nd-map-label">{feature.name}</span>
              ) : null}
            </div>
          );
        })}
      </div>
      <figcaption className="nd-caption">
        <span className="nd-key">
          <span className="nd-key-swatch nd-key-swatch--open" aria-hidden="true" />
          the insert the seven steps chose
        </span>
        <span className="nd-key">
          <span
            className="nd-key-swatch nd-key-swatch--capped"
            aria-hidden="true"
          />
          backbone: marker, promoter, terminator, arms
        </span>
      </figcaption>
    </figure>
  );
}

/* ---------- the walkthrough ---------- */

/** How many surviving candidates the screen and the construct carry. Ten rows
 * is a matrix a reader can still take in; three windows is what our own
 * loop-ended construct holds. */
const SCREEN_LIMIT = 10;
const CARRY_LIMIT = 3;

export function NectarDesigner() {
  const uid = useId();
  const combClip = `${uid}-comb`;
  const foldClip = `${uid}-fold`;
  const glowId = `${uid}-glow`;
  const dockClip = `${uid}-dock`;
  const hatch = `${uid}-hatch`;

  /** Identity or accessibility, the original's two views of the same fold. */
  const [colourMode, setColourMode] = useState<"base" | "accessibility">("base");

  /* A link can name a step: /software#nectar-designer-4 opens on the fold.
   * Read once, during the first render rather than in an effect, so a link
   * into step 4 never shows step 1 for a frame first. The hash is not written
   * back as the reader steps, because that would either pile up history
   * entries or fight the wiki's own ScrollToHash on the next navigation. */
  const [step, setStep] = useState(() => {
    if (typeof window === "undefined") return 1;
    const asked = Number(
      /^#nectar-designer-(\d+)$/.exec(window.location.hash)?.[1],
    );
    return Number.isInteger(asked) && asked >= 1 && asked <= STEPS.length
      ? asked
      : 1;
  });
  const [motion, setMotion] = useState(() => !prefersReducedMotion());
  const railRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const root = useRef<HTMLDivElement>(null);

  /* ScrollToHash cannot help here: it looks for an element whose id is the
   * whole fragment, and "nectar-designer-4" is never an element. So the
   * component puts itself on screen when a link named one of its steps. */
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!/^#nectar-designer-\d+$/.test(window.location.hash)) return;
    const id = requestAnimationFrame(() =>
      root.current?.scrollIntoView({ block: "start" }),
    );
    return () => cancelAnimationFrame(id);
  }, []);

  const [organismId, setOrganismId] = useState("org-varroa");
  const [targetClass, setTargetClass] = useState<TargetClass>("essential");
  const [numCandidates, setNumCandidates] = useState(8);
  const [geneId, setGeneId] = useState<string | null>(null);
  const [seedFiltering, setSeedFiltering] = useState(true);
  const [threshold, setThreshold] = useState(19);
  const [panelIds, setPanelIds] = useState<string[]>(() => [
    ...suggestedPanelFor("org-varroa"),
    "org-human",
  ]);
  const [chassis, setChassis] = useState<DeliveryChassis>("s-cerevisiae");
  const [topology, setTopology] = useState<CassetteTopology>("dumbbell");
  const [promoterId, setPromoterId] = useState(() =>
    defaultPromoterId("s-cerevisiae"),
  );
  const [markerId, setMarkerId] = useState(() => defaultMarkerId("s-cerevisiae"));
  const [candidateId, setCandidateId] = useState<string | null>(null);
  /** Golden Gate removals, tied to the design they were made on so a changed
   * construct starts clean instead of inheriting edits to a different one. */
  const [removed, setRemoved] = useState<{ designId: string; sites: number[] }>({
    designId: "",
    sites: [],
  });

  const organism = getOrganism(organismId);
  const lengthSpec = lengthForOrganism(organismId);
  const recommended = useMemo(
    () => new Set(suggestedPanelFor(organismId)),
    [organismId],
  );

  function chooseOrganism(id: string) {
    setOrganismId(id);
    setGeneId(null);
    setCandidateId(null);
    setPanelIds([...suggestedPanelFor(id), "org-human"]);
  }

  function chooseChassis(next: DeliveryChassis) {
    setChassis(next);
    setPromoterId(defaultPromoterId(next));
    setMarkerId(defaultMarkerId(next));
  }

  function reset() {
    chooseOrganism("org-varroa");
    setTargetClass("essential");
    setNumCandidates(8);
    setSeedFiltering(true);
    setThreshold(19);
    chooseChassis("s-cerevisiae");
    setTopology("dumbbell");
    setRemoved({ designId: "", sites: [] });
    setStep(1);
  }

  // Step 3: the ranked gene list.
  const genes = useMemo(
    () => discoverTargets(organismId, targetClass, numCandidates),
    [organismId, targetClass, numCandidates],
  );
  const gene = genes.find((one) => one.id === geneId) ?? genes[0] ?? null;

  // Step 4: the fold, and the windows tiled against it.
  const fold = useMemo(() => (gene ? getFold(gene.transcriptId) : null), [gene]);
  const tiled = useMemo(
    () =>
      gene ? tileSirnas(gene.transcriptId, lengthSpec.length, seedFiltering) : [],
    [gene, lengthSpec.length, seedFiltering],
  );
  const filteredOut = tiled.filter((one) => one.isSeedFiltered).length;
  const screened = useMemo(
    () => tiled.filter((one) => !one.isSeedFiltered).slice(0, SCREEN_LIMIT),
    [tiled],
  );
  const candidate =
    screened.find((one) => one.id === candidateId) ?? screened[0] ?? null;

  /* The stretch the FOLD draws, and only the fold. The comb below it always
   * shows the whole transcript. With no window chosen this opens on the first
   * 150 nucleotides; choosing one narrows to it plus 40 either side. Both
   * numbers are the original tool's. */
  const foldRange = useMemo(() => {
    if (!fold) return null;
    const total = fold.sequence.length;
    if (!candidate) {
      return { from: 0, to: Math.min(FOLD_DEFAULT_SPAN, total) };
    }
    return {
      from: Math.max(0, candidate.position - FOLD_PAD),
      to: Math.min(total, candidate.position + candidate.length + FOLD_PAD),
    };
  }, [fold, candidate]);

  // Step 5: the safety screen.
  const panel = useMemo(
    () =>
      panelIds
        .map((id) => getOrganism(id))
        .filter((one): one is NonNullable<typeof one> => Boolean(one)),
    [panelIds],
  );
  const report = useMemo(
    () => screenOffTargets(screened, panelIds, threshold),
    [screened, panelIds, threshold],
  );
  const survivors = useMemo(
    () => screened.filter((one) => report.survivorIds.includes(one.id)),
    [screened, report],
  );

  /* The sweep: species are checked one at a time when you arrive at step 5, so
   * a rejection is something you watch happen rather than a table that was
   * always red. It only runs while step 5 is the one on screen. */
  const [swept, setSwept] = useState(0);
  useEffect(() => {
    if (step !== 5) return;
    if (!motion) {
      setSwept(panel.length);
      return;
    }
    setSwept(0);
    let i = 0;
    const id = window.setInterval(() => {
      i += 1;
      setSwept(i);
      if (i >= panel.length) window.clearInterval(id);
    }, 300);
    return () => window.clearInterval(id);
  }, [step, motion, panel.length, threshold, screened]);
  const sweepDone = swept >= panel.length;

  // Step 6: what the survivors can be built into.
  const carried = useMemo(
    () => (survivors.length > 0 ? survivors : screened).slice(0, CARRY_LIMIT),
    [survivors, screened],
  );
  const baseDesign = useMemo(
    () =>
      carried.length > 0
        ? buildCassette(carried, chassis, topology, promoterId, markerId)
        : null,
    [carried, chassis, topology, promoterId, markerId],
  );
  const design = useMemo(() => {
    if (!baseDesign) return null;
    if (removed.designId !== baseDesign.id) return baseDesign;
    return removed.sites.reduce(
      (acc, index) => removeGoldenGateSite(acc, index),
      baseDesign,
    );
  }, [baseDesign, removed]);
  const openSites = design
    ? design.goldenGateSites.filter((one) => !one.removed).length
    : 0;

  const cellFor = (candidateKey: string, speciesId: string) =>
    report.cells.find(
      (one) => one.candidateId === candidateKey && one.speciesId === speciesId,
    );

  const current = STEPS[step - 1];

  return (
    <div className="nd" id="nectar-designer" ref={root}>
      <div className="nd-toolbar">
        <p className="nd-toolbar-note">
          Seven decisions, one at a time. Every control re-runs the steps after
          it.
        </p>
        <div className="nd-toolbar-buttons">
          {/* The page opens on this figure, so the full note about where its
              numbers come from sits under it rather than over it. This tag is
              what keeps that honest: it rides the tool's own header, so a
              reader never meets a sequence or a score without something on
              screen saying it was generated. The standalone version of this
              tool carried the same marker in the same place. */}
          <span className="nd-tag" title="Every value in this figure is produced by a seeded generator. The full note is directly below the figure.">
            Generated data, not measured
          </span>
          <button
            type="button"
            className="nd-button is-quiet"
            aria-pressed={!motion}
            onClick={() => setMotion((on) => !on)}
          >
            {motion ? "Motion on" : "Motion off"}
          </button>
          <button type="button" className="nd-button" onClick={reset}>
            Reset
          </button>
        </div>
      </div>

      {/* ---------- the rail ---------- */}

      <div
        className="nd-rail"
        role="tablist"
        aria-label="Design pipeline steps"
        onKeyDown={(event) => {
          if (event.key !== "ArrowRight" && event.key !== "ArrowLeft") return;
          event.preventDefault();
          const next =
            event.key === "ArrowRight"
              ? Math.min(STEPS.length, step + 1)
              : Math.max(1, step - 1);
          setStep(next);
          railRefs.current[next - 1]?.focus();
        }}
      >
        {STEPS.map((one) => {
          const on = one.n === step;
          return (
            <button
              key={one.n}
              type="button"
              role="tab"
              aria-selected={on}
              tabIndex={on ? 0 : -1}
              ref={(el) => {
                railRefs.current[one.n - 1] = el;
              }}
              className="nd-rail-step"
              onClick={() => setStep(one.n)}
            >
              <svg viewBox="0 0 28 24.25" width="30" height="26" aria-hidden="true">
                <polygon
                  points={hexPoints(0, 0, 28)}
                  className="nd-rail-cell"
                />
                <text x="14" y="12.12" dominantBaseline="central" textAnchor="middle">
                  {one.n}
                </text>
              </svg>
              <span className="nd-rail-label">{one.label}</span>
            </button>
          );
        })}
      </div>

      {/* ---------- the one step on screen ---------- */}

      <div
        className="nd-stage"
        role="tabpanel"
        aria-label={`Step ${current.n}: ${current.title}`}
        /* Keyed on the step so the arrival animation replays on every switch. */
        key={motion ? step : "still"}
        data-motion={motion ? "on" : "off"}
      >
        <header className="nd-step-head">
          <div>
            <h3>
              <span className="nd-step-ordinal">Step {current.n}.</span>{" "}
              {current.title}
            </h3>
            <p className="nd-step-decides">{current.decides}</p>
          </div>
        </header>

        <div className="nd-body">
          {/* ---------- 1 ---------- */}
          {step === 1 ? (
            <>
              <Field
                label="Pest"
                hint="Varroa is our case study. The others are here because only the input changes."
              >
                <div className="nd-chips">
                  {TARGET_ORGANISMS.map((one) => (
                    <button
                      key={one.id}
                      type="button"
                      className="nd-chip"
                      aria-pressed={organismId === one.id}
                      onClick={() => chooseOrganism(one.id)}
                    >
                      {one.commonName}
                    </button>
                  ))}
                </div>
              </Field>

              {organism ? (
                <p className="nd-fact">
                  <em>{organism.scientificName}</em>, taxonomy id{" "}
                  {organism.taxid}, about{" "}
                  {organism.transcriptCount.toLocaleString()} transcripts in the
                  reference set.
                </p>
              ) : null}

              <Field label="Class of gene">
                <div className="nd-chips">
                  {TARGET_CLASSES.map((one) => (
                    <button
                      key={one.id}
                      type="button"
                      className="nd-chip"
                      aria-pressed={targetClass === one.id}
                      onClick={() => {
                        setTargetClass(one.id);
                        setGeneId(null);
                        setCandidateId(null);
                      }}
                    >
                      {one.title}
                    </button>
                  ))}
                </div>
              </Field>
              <p className="nd-fact">
                {TARGET_CLASSES.find((one) => one.id === targetClass)?.description}
              </p>
            </>
          ) : null}

          {/* ---------- 2 ---------- */}
          {step === 2 ? (
            <>
              <div className="nd-derived">
                <span className="nd-derived-value">{lengthSpec.length} nt</span>
                <span className="nd-derived-label">
                  duplex length, derived from the target rather than dialled
                </span>
                <p>{lengthSpec.note}</p>
              </div>

              <Field label={`Candidate genes to rank: ${numCandidates}`}>
                <input
                  type="range"
                  min={3}
                  max={12}
                  value={numCandidates}
                  className="nd-range"
                  onChange={(event) => {
                    setNumCandidates(Number(event.target.value));
                    setGeneId(null);
                  }}
                />
              </Field>

              <Field
                label={`Off-target threshold: ${threshold} nt contiguous match`}
                hint={
                  threshold <= 17
                    ? "Very strict. Almost any partial homology counts, and more candidates die."
                    : threshold <= 20
                      ? "The conventional cutoff for a match long enough to load and silence."
                      : "Permissive. Only long, near-exact matches count, which is faster and leaves more residual risk."
                }
              >
                <input
                  type="range"
                  min={15}
                  max={25}
                  value={threshold}
                  className="nd-range"
                  onChange={(event) => setThreshold(Number(event.target.value))}
                />
              </Field>

              <Field
                label="Species that must not be affected"
                hint="Marked species share a habitat or a trophic link with the pest. Two have no reference transcriptome and cannot be screened."
              >
                <div className="nd-chips">
                  {SCREENABLE_POOL.map((one) => {
                    const on = panelIds.includes(one.id);
                    const blocked = !one.hasReferenceTranscriptome;
                    return (
                      <button
                        key={one.id}
                        type="button"
                        className={blocked ? "nd-chip is-unscreenable" : "nd-chip"}
                        aria-pressed={on}
                        onClick={() =>
                          setPanelIds((now) =>
                            now.includes(one.id)
                              ? now.filter((id) => id !== one.id)
                              : [...now, one.id],
                          )
                        }
                      >
                        {recommended.has(one.id) ? (
                          <span className="nd-chip-mark" aria-hidden="true" />
                        ) : null}
                        {one.commonName}
                        {blocked ? (
                          <span className="nd-chip-tag">no reference</span>
                        ) : null}
                      </button>
                    );
                  })}
                </div>
              </Field>

              <label className="nd-switch">
                <input
                  type="checkbox"
                  checked={seedFiltering}
                  onChange={(event) => setSeedFiltering(event.target.checked)}
                />
                <span>
                  <strong>Seed-region filtering.</strong> Rejects windows whose
                  guide has a repetitive motif at positions 2 to 8.
                </span>
              </label>
            </>
          ) : null}

          {/* ---------- 3 ---------- */}
          {step === 3 ? (
            <>
              <p className="nd-fact">
                The real ranking combines protein-interaction centrality with
                transcript abundance. Choose a row to carry it forward.
              </p>
              <div className="nd-scroll">
                <table className="nd-table">
                  <caption className="nd-table-caption">
                    Candidate genes for {organism?.commonName ?? "the target"},{" "}
                    {TARGET_CLASSES.find(
                      (one) => one.id === targetClass,
                    )?.title.toLowerCase()}
                    .
                  </caption>
                  <thead>
                    <tr>
                      <th scope="col">Carry</th>
                      <th scope="col">Symbol</th>
                      <th scope="col">Accession</th>
                      <th scope="col">Length</th>
                      <th scope="col">Conservation</th>
                      <th scope="col">Expression</th>
                      <th scope="col">Product</th>
                    </tr>
                  </thead>
                  <tbody>
                    {genes.map((one) => (
                      <tr
                        key={one.id}
                        className={gene?.id === one.id ? "is-chosen" : undefined}
                      >
                        <td>
                          <button
                            type="button"
                            className="nd-pick"
                            aria-pressed={gene?.id === one.id}
                            onClick={() => {
                              setGeneId(one.id);
                              setCandidateId(null);
                            }}
                          >
                            {gene?.id === one.id ? "carried" : "carry"}
                          </button>
                        </td>
                        <th scope="row">{one.symbol}</th>
                        <td>{one.accession}</td>
                        <td className="nd-num">
                          {one.lengthNt.toLocaleString()} nt
                        </td>
                        <td className="nd-num">
                          {Math.round(one.conservationScore * 100)}%
                        </td>
                        <td>{one.expressionEvidence}</td>
                        <td>{one.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          ) : null}

          {/* ---------- 4 ---------- */}
          {step === 4 ? (
            fold && gene && foldRange ? (
              <>
                <p className="nd-fact">
                  {gene.symbol}, {fold.sequence.length.toLocaleString()} nt. A
                  window buried inside a stem is not a usable window, so the fold
                  comes before the scoring.
                </p>

                <figure className="nd-figure">
                  <div className="nd-fold-modes">
                    <span className="nd-field-label">Colour the bases by</span>
                    <div className="nd-chips">
                      <button
                        type="button"
                        className="nd-chip"
                        aria-pressed={colourMode === "base"}
                        onClick={() => setColourMode("base")}
                      >
                        Identity
                      </button>
                      <button
                        type="button"
                        className="nd-chip"
                        aria-pressed={colourMode === "accessibility"}
                        onClick={() => setColourMode("accessibility")}
                      >
                        Accessibility
                      </button>
                    </div>
                  </div>

                  <FoldedStructure
                    profile={fold}
                    from={foldRange.from}
                    to={foldRange.to}
                    markFrom={candidate ? candidate.position : null}
                    markTo={
                      candidate ? candidate.position + candidate.length : null
                    }
                    markLabel={
                      candidate
                        ? `${Math.round(candidate.efficacyScore * 100)}% score`
                        : undefined
                    }
                    colourMode={colourMode}
                    motion={motion}
                    clipId={foldClip}
                    glowId={glowId}
                    runKey={`${gene.transcriptId}:${foldRange.from}:${foldRange.to}`}
                  />

                  {/* One line under the figure, and one key. The mechanism, the
                      provenance and the ViennaRNA note all live in the page
                      prose below, so repeating them here only buried the
                      figure. */}
                  <figcaption className="nd-caption">
                    <span className="nd-key">
                      Nucleotides {(foldRange.from + 1).toLocaleString()} to{" "}
                      {foldRange.to.toLocaleString()} of{" "}
                      {fold.sequence.length.toLocaleString()}
                    </span>
                    {colourMode === "base" ? (
                      (["A", "U", "G", "C"] as const).map((base) => (
                        <span className="nd-key" key={base}>
                          <span
                            className="nd-key-swatch"
                            style={{ background: BASE_COLOURS[base] }}
                            aria-hidden="true"
                          />
                          {base}
                        </span>
                      ))
                    ) : (
                      <>
                        <span className="nd-key">
                          <span
                            className="nd-key-swatch"
                            style={{ background: accessibilityColour(0) }}
                            aria-hidden="true"
                          />
                          occluded
                        </span>
                        <span className="nd-key">
                          <span
                            className="nd-key-swatch"
                            style={{ background: accessibilityColour(1) }}
                            aria-hidden="true"
                          />
                          open
                        </span>
                      </>
                    )}
                    <span className="nd-key">
                      <span
                        className="nd-key-swatch nd-key-swatch--wax"
                        aria-hidden="true"
                      />
                      capped
                    </span>
                  </figcaption>
                </figure>

                {/* The whole transcript, as a locator. It carries one line of
                    chrome, because the capping it uses is already keyed under
                    the fold and a second key for the same idea was noise. */}
                <figure className="nd-figure">
                  <AccessibilityComb
                    unpaired={fold.unpairedProbability}
                    from={0}
                    to={fold.sequence.length}
                    markedFrom={foldRange.from}
                    markedTo={foldRange.to}
                    clipId={combClip}
                  />
                  <figcaption className="nd-comb-axis">
                    <span>1</span>
                    <span>
                      the whole transcript, with the drawn stretch outlined
                    </span>
                    <span>{fold.sequence.length.toLocaleString()}</span>
                  </figcaption>
                </figure>

                <p className="nd-fact">
                  {tiled.length.toLocaleString()} windows tiled at{" "}
                  {lengthSpec.length} nt.{" "}
                  {seedFiltering
                    ? `${filteredOut.toLocaleString()} rejected on seed-region risk before scoring.`
                    : "Seed-region filtering is off, so nothing was rejected before scoring."}{" "}
                  The ten best go forward.
                </p>

                <div className="nd-scroll">
                  <table className="nd-table">
                    <caption className="nd-table-caption">
                      The ten best-scoring windows in {gene.symbol}. Choose one to
                      watch it dock.
                    </caption>
                    <thead>
                      <tr>
                        <th scope="col">Inspect</th>
                        <th scope="col">Position</th>
                        <th scope="col">Sense sequence</th>
                        <th scope="col">Score</th>
                        <th scope="col">Accessible</th>
                      </tr>
                    </thead>
                    <tbody>
                      {screened.map((one) => (
                        <tr
                          key={one.id}
                          className={
                            candidate?.id === one.id ? "is-chosen" : undefined
                          }
                        >
                          <td>
                            <button
                              type="button"
                              className="nd-pick"
                              aria-pressed={candidate?.id === one.id}
                              onClick={() => setCandidateId(one.id)}
                            >
                              {candidate?.id === one.id ? "shown" : "show"}
                            </button>
                          </td>
                          <td className="nd-num">
                            {one.position.toLocaleString()}
                          </td>
                          <th scope="row" className="nd-seq">
                            {one.senseSeq}
                          </th>
                          <td className="nd-num">
                            {Math.round(one.efficacyScore * 100)}
                          </td>
                          <td className="nd-num">
                            {Math.round(one.accessibility * 100)}%
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {candidate ? (
                  <DockingView
                    candidate={candidate}
                    sequence={fold.sequence}
                    motion={motion}
                    clipId={dockClip}
                  />
                ) : null}
              </>
            ) : (
              <p className="nd-fact">
                No gene selected, so there is nothing to fold.
              </p>
            )
          ) : null}

          {/* ---------- 5 ---------- */}
          {step === 5 ? (
            <>
              <p className="nd-fact">
                {screened.length} windows against {panel.length} species,
                rejecting any window with a contiguous match of {threshold} nt or
                more.{" "}
                {sweepDone ? (
                  <strong>
                    {survivors.length} of {screened.length} survive.
                  </strong>
                ) : (
                  <span className="nd-sweeping">
                    Screening {panel[swept]?.commonName ?? ""}
                  </span>
                )}{" "}
                This is the step where safety is part of the design rather than
                an assessment bolted on afterwards.
              </p>

              {report.unscreenableSpeciesIds.length > 0 ? (
                <p className="nd-flag">
                  {report.unscreenableSpeciesIds.length === 1
                    ? "One species in this panel has"
                    : `${report.unscreenableSpeciesIds.length} species in this panel have`}{" "}
                  no reference transcriptome. Their column is hatched: absence of
                  a hit there is absence of data, not a pass.
                </p>
              ) : null}

              {panel.length === 0 ? (
                <p className="nd-flag">
                  No species are selected, so nothing is being screened and every
                  window survives by default. Choose a panel in step 2.
                </p>
              ) : (
                <>
                  <figure className="nd-figure">
                    <svg
                      viewBox={`0 0 ${MATRIX_LEFT + panel.length * MATRIX_COL + 4} ${MATRIX_TOP + screened.length * MATRIX_ROW + 4}`}
                      width={MATRIX_LEFT + panel.length * MATRIX_COL + 4}
                      height={MATRIX_TOP + screened.length * MATRIX_ROW + 4}
                      className="nd-matrix"
                      role="img"
                      aria-label={`Screening matrix, ${screened.length} windows down the side against ${panel.length} species across the top. Every value is repeated in the table below.`}
                    >
                      <defs>
                        <pattern
                          id={hatch}
                          width="6"
                          height="6"
                          patternUnits="userSpaceOnUse"
                          patternTransform="rotate(45)"
                        >
                          <rect width="6" height="6" className="nd-hatch-ground" />
                          <line
                            x1="0"
                            y1="0"
                            x2="0"
                            y2="6"
                            className="nd-hatch-line"
                          />
                        </pattern>
                      </defs>

                      {panel.map((species, col) => {
                        const x = MATRIX_LEFT + col * MATRIX_COL + MATRIX_CELL / 2;
                        const y = MATRIX_TOP - 8;
                        return (
                          <text
                            key={species.id}
                            x={x}
                            y={y}
                            className={
                              col < swept
                                ? "nd-matrix-label"
                                : "nd-matrix-label is-waiting"
                            }
                            transform={`rotate(-60 ${x} ${y})`}
                          >
                            {species.commonName}
                          </text>
                        );
                      })}

                      {screened.map((one, row) => (
                        <text
                          key={`n${one.id}`}
                          x={MATRIX_LEFT - 8}
                          y={
                            MATRIX_TOP +
                            row * MATRIX_ROW +
                            (MATRIX_CELL * HEX_RATIO) / 2
                          }
                          dominantBaseline="central"
                          textAnchor="end"
                          className="nd-matrix-row"
                        >
                          {row + 1}
                        </text>
                      ))}

                      {screened.map((one, row) =>
                        panel.map((species, col) => {
                          const cell = cellFor(one.id, species.id);
                          if (!cell) return null;
                          const shown = col < swept;
                          const state = cellState(
                            cell.longestMatch,
                            cell.isHit,
                            cell.unscreenable,
                            threshold,
                          );
                          return (
                            <polygon
                              key={`${one.id}-${species.id}`}
                              points={hexPoints(
                                MATRIX_LEFT + col * MATRIX_COL,
                                MATRIX_TOP + row * MATRIX_ROW,
                                MATRIX_CELL,
                              )}
                              className={
                                shown
                                  ? `nd-cell nd-cell--${state}`
                                  : "nd-cell nd-cell--waiting"
                              }
                              fill={
                                shown && state === "unscreenable"
                                  ? `url(#${hatch})`
                                  : undefined
                              }
                            >
                              <title>
                                {shown
                                  ? `Window ${row + 1} (${one.senseSeq}) against ${species.commonName}: ${
                                      cell.unscreenable
                                        ? "no reference transcriptome, not screened"
                                        : `longest contiguous match ${cell.longestMatch} nt, ${STATE_WORD[state]}`
                                    }`
                                  : `Window ${row + 1} against ${species.commonName}: not yet screened`}
                              </title>
                            </polygon>
                          );
                        }),
                      )}
                    </svg>
                    <figcaption className="nd-caption">
                      <span className="nd-key">
                        <span
                          className="nd-key-swatch nd-key-swatch--pass"
                          aria-hidden="true"
                        />
                        clear
                      </span>
                      <span className="nd-key">
                        <span
                          className="nd-key-swatch nd-key-swatch--caution"
                          aria-hidden="true"
                        />
                        within 30% of the threshold
                      </span>
                      <span className="nd-key">
                        <span
                          className="nd-key-swatch nd-key-swatch--hit"
                          aria-hidden="true"
                        />
                        at or over the threshold, rejected
                      </span>
                      <span className="nd-key">
                        <span
                          className="nd-key-swatch nd-key-swatch--unscreenable"
                          aria-hidden="true"
                        />
                        no reference, not screened
                      </span>
                    </figcaption>
                  </figure>

                  <div className="nd-scroll">
                    <table className="nd-table">
                      <caption className="nd-table-caption">
                        Longest contiguous match in nucleotides, per window and
                        species. Blank means the species has no reference to
                        screen against.
                      </caption>
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Window</th>
                          {panel.map((species) => (
                            <th scope="col" key={species.id}>
                              {species.commonName}
                            </th>
                          ))}
                          <th scope="col">Outcome</th>
                        </tr>
                      </thead>
                      <tbody>
                        {screened.map((one, row) => {
                          const kept = report.survivorIds.includes(one.id);
                          return (
                            <tr
                              key={one.id}
                              className={
                                sweepDone && !kept ? "is-out" : undefined
                              }
                            >
                              <td className="nd-num">{row + 1}</td>
                              <th scope="row" className="nd-seq">
                                {one.senseSeq}
                              </th>
                              {panel.map((species) => {
                                const cell = cellFor(one.id, species.id);
                                return (
                                  <td className="nd-num" key={species.id}>
                                    {cell?.unscreenable
                                      ? ""
                                      : (cell?.longestMatch ?? "")}
                                  </td>
                                );
                              })}
                              <td>
                                {!sweepDone ? "" : kept ? "kept" : "rejected"}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </>
              )}
            </>
          ) : null}

          {/* ---------- 6 ---------- */}
          {step === 6 ? (
            <>
              <Field label="Production chassis" hint={CHASSIS_NOTES[chassis]}>
                <div className="nd-chips">
                  {CHASSIS_ORDER.map((one) => (
                    <button
                      key={one}
                      type="button"
                      className="nd-chip"
                      aria-pressed={chassis === one}
                      onClick={() => chooseChassis(one)}
                    >
                      {CHASSIS_LABELS[one]}
                    </button>
                  ))}
                </div>
              </Field>

              <Field
                label="Architecture"
                hint={TOPOLOGIES.find((one) => one.id === topology)?.note}
              >
                <div className="nd-chips">
                  {TOPOLOGIES.map((one) => (
                    <button
                      key={one.id}
                      type="button"
                      className="nd-chip"
                      aria-pressed={topology === one.id}
                      onClick={() => setTopology(one.id)}
                    >
                      {one.label}
                    </button>
                  ))}
                </div>
              </Field>

              {topology === "dumbbell" ? (
                <p className="nd-fact">
                  The dumbbell needs no promoter, terminator or marker, because
                  nothing transcribes it inside a cell. That is why those
                  controls are absent rather than disabled.
                </p>
              ) : (
                <div className="nd-pair">
                  <Field label="Promoter">
                    <div className="nd-chips">
                      {PROMOTERS_BY_CHASSIS[chassis].map((one) => (
                        <button
                          key={one.id}
                          type="button"
                          className="nd-chip"
                          aria-pressed={promoterId === one.id}
                          onClick={() => setPromoterId(one.id)}
                        >
                          {one.label}
                        </button>
                      ))}
                    </div>
                  </Field>
                  <Field label="Selectable marker">
                    <div className="nd-chips">
                      {MARKERS_BY_CHASSIS[chassis].map((one) => (
                        <button
                          key={one.id}
                          type="button"
                          className="nd-chip"
                          aria-pressed={markerId === one.id}
                          onClick={() => setMarkerId(one.id)}
                        >
                          {one.label}
                        </button>
                      ))}
                    </div>
                  </Field>
                </div>
              )}

              {design ? (
                <>
                  <p className="nd-fact">
                    {design.lengthBp.toLocaleString()} bp, carrying{" "}
                    {carried.length} {carried.length === 1 ? "window" : "windows"}
                    . Only promoters and markers valid in{" "}
                    {CHASSIS_LABELS[chassis]} are offered.
                  </p>

                  <FeatureMap design={design} />

                  <div className="nd-scroll">
                    <table className="nd-table">
                      <caption className="nd-table-caption">
                        Every feature on the construct, in order.
                      </caption>
                      <thead>
                        <tr>
                          <th scope="col">Feature</th>
                          <th scope="col">Type</th>
                          <th scope="col">From</th>
                          <th scope="col">To</th>
                          <th scope="col">Length</th>
                          <th scope="col">Strand</th>
                        </tr>
                      </thead>
                      <tbody>
                        {design.features.map((one) => (
                          <tr key={one.id}>
                            <th scope="row">{one.name}</th>
                            <td>{one.type.replace("-", " ")}</td>
                            <td className="nd-num">{one.start + 1}</td>
                            <td className="nd-num">{one.end}</td>
                            <td className="nd-num">{one.end - one.start} bp</td>
                            <td>{one.strand === 1 ? "forward" : "reverse"}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  <h4 className="nd-subhead">Assembly sites</h4>
                  {design.goldenGateSites.length === 0 ? (
                    <p className="nd-fact">
                      No BsaI, BsmBI or SapI recognition sites in the construct,
                      so it is clean for Golden Gate assembly as it stands.
                    </p>
                  ) : (
                    <>
                      <p className="nd-fact">
                        {openSites === 0
                          ? "Every recognition site has been broken. The construct is clean for Golden Gate assembly."
                          : `${openSites} recognition ${openSites === 1 ? "site" : "sites"} would cut this construct during assembly. Breaking one flips a single interior base.`}
                      </p>
                      <ul className="nd-sites">
                        {design.goldenGateSites.map((site, index) => (
                          <li key={`${site.enzyme}-${site.position}`}>
                            <span className="nd-seq">{site.sequence}</span>{" "}
                            {site.enzyme} at {site.position + 1}
                            {site.removed ? (
                              <span className="nd-site-done">broken</span>
                            ) : (
                              <button
                                type="button"
                                className="nd-pick"
                                onClick={() =>
                                  setRemoved((now) => ({
                                    designId: baseDesign?.id ?? "",
                                    sites:
                                      now.designId === baseDesign?.id
                                        ? [...now.sites, index]
                                        : [index],
                                  }))
                                }
                              >
                                break it
                              </button>
                            )}
                          </li>
                        ))}
                      </ul>
                    </>
                  )}
                </>
              ) : (
                <p className="nd-fact">
                  Nothing survived the screen, so there is no construct to build.
                  Loosen the threshold in step 2 or drop a species from the panel.
                </p>
              )}
            </>
          ) : null}

          {/* ---------- 7 ---------- */}
          {step === 7 ? (
            design ? (
              <>
                <p className="nd-fact">
                  Written in the browser. Each file says inside itself that the
                  sequence is generated.
                </p>
                <div className="nd-downloads">
                  <button
                    type="button"
                    className="nd-button"
                    onClick={() =>
                      downloadText(
                        "nectar-designer-demo.gb",
                        buildGenBank(design),
                        "text/plain",
                      )
                    }
                  >
                    GenBank, annotated
                  </button>
                  <button
                    type="button"
                    className="nd-button"
                    onClick={() =>
                      downloadText(
                        "nectar-designer-demo.fasta",
                        buildFasta(design),
                        "text/plain",
                      )
                    }
                  >
                    FASTA, sequence only
                  </button>
                  <button
                    type="button"
                    className="nd-button"
                    onClick={() =>
                      downloadText(
                        "nectar-designer-demo-primers.csv",
                        primersToCsv(buildPrimers(design, carried)),
                        "text/csv",
                      )
                    }
                  >
                    Check primers, CSV
                  </button>
                </div>

                <h4 className="nd-subhead">This run, in one place</h4>
                <dl className="nd-summary">
                  <div>
                    <dt>Target</dt>
                    <dd>
                      {organism?.commonName} ({organism?.scientificName})
                    </dd>
                  </div>
                  <div>
                    <dt>Gene carried</dt>
                    <dd>{gene ? `${gene.symbol}, ${gene.description}` : "none"}</dd>
                  </div>
                  <div>
                    <dt>Duplex length</dt>
                    <dd>{lengthSpec.length} nt</dd>
                  </div>
                  <div>
                    <dt>Windows tiled</dt>
                    <dd>{tiled.length.toLocaleString()}</dd>
                  </div>
                  <div>
                    <dt>Screened against</dt>
                    <dd>
                      {panel.length} species at {threshold} nt
                    </dd>
                  </div>
                  <div>
                    <dt>Survived</dt>
                    <dd>
                      {survivors.length} of {screened.length}
                    </dd>
                  </div>
                  <div>
                    <dt>Construct</dt>
                    <dd>
                      {TOPOLOGIES.find((one) => one.id === topology)?.label},{" "}
                      {design.lengthBp.toLocaleString()} bp in{" "}
                      {CHASSIS_LABELS[chassis]}
                    </dd>
                  </div>
                  <div>
                    <dt>Open assembly sites</dt>
                    <dd>{openSites}</dd>
                  </div>
                </dl>

                <h4 className="nd-subhead">GenBank, as written</h4>
                <pre
                  className="nd-preview"
                  tabIndex={0}
                  aria-label="GenBank file preview"
                >
                  {buildGenBank(design).split("\n").slice(0, 24).join("\n")}
                  {"\n..."}
                </pre>
              </>
            ) : (
              <p className="nd-fact">
                There is no construct to export. Loosen the screen in step 2.
              </p>
            )
          ) : null}
        </div>
      </div>

      {/* ---------- moving between steps ---------- */}

      <nav className="nd-move" aria-label="Move between steps">
        <button
          type="button"
          className="nd-button is-quiet"
          disabled={step === 1}
          onClick={() => setStep((n) => Math.max(1, n - 1))}
        >
          Back
        </button>
        <span className="nd-move-where">
          {step} of {STEPS.length}
        </span>
        <button
          type="button"
          className="nd-button"
          disabled={step === STEPS.length}
          onClick={() => setStep((n) => Math.min(STEPS.length, n + 1))}
        >
          {step === STEPS.length ? "Done" : `Next: ${STEPS[step].label}`}
        </button>
      </nav>

      {/* Under the figure rather than over it, because the page leads with the
          figure. The tag in the toolbar above is what stops a number ever
          appearing with nothing on screen to qualify it. */}
      <p className="nd-warning">
        <strong>Generated demonstration data.</strong> Every sequence, score,
        fold and screening result above is produced by a seeded generator in the
        browser so that the pipeline&rsquo;s shape can be driven and checked.
        None of it is a biological prediction, none of it is an experimental
        result, and the files it offers you say so inside themselves. Our real
        ranking weights, thresholds and training corpus are held back pending
        the IP position. Team data replaces this when the gate closes.
      </p>
    </div>
  );
}
