/* Static reference data for the NectarDesigner walkthrough on /software.
 *
 * WHAT IS REAL HERE AND WHAT IS NOT.
 *
 * Real: the species list and their NCBI taxonomy ids, the chassis/promoter/
 * marker compatibility tables, the Dicer-2 product lengths, and which
 * non-target species are worth screening against which pest. That is ordinary
 * domain reference data, the same table a live backend would need.
 *
 * NOT real: transcript counts are plausible round numbers, not counts we
 * verified, and every sequence, score, fold and off-target hit the walkthrough
 * shows is generated by the seeded generator in src/utils/rnaDesign.ts. The
 * component says so on its face and the page says so in prose. Nothing here is
 * a measurement and nothing here is a prediction.
 *
 * The gene names below are a curated pool so a candidate list reads like a
 * screen instead of "Gene 1, Gene 2". They are NOT our target. The real
 * Varroa target is not named anywhere on this wiki pending the IP position
 * (see the holdback note on /software), and this demo does not name it either.
 */

export type TargetClass =
  | "essential"
  | "population-control"
  | "developmental";

export type DeliveryChassis =
  | "s-cerevisiae"
  | "ecoli-ht115"
  | "snodgrassella-alvi";

export type SirnaLength = 19 | 21 | 22 | 24;

export interface Organism {
  id: string;
  commonName: string;
  scientificName: string;
  taxid: number;
  /** Plausible order of magnitude, not a verified count. */
  transcriptCount: number;
  /** false => cannot be screened, and the matrix says so rather than passing it. */
  hasReferenceTranscriptome: boolean;
  kind: "target" | "non-target" | "human";
}

/* ---------- species ---------- */

/** Pests selectable as a design target. Varroa leads: it is our case study,
 * and the seven others are the platform claim made checkable — the same
 * pipeline, a different organism. */
export const TARGET_ORGANISMS: Organism[] = [
  {
    id: "org-varroa",
    commonName: "Varroa mite",
    scientificName: "Varroa destructor",
    taxid: 109461,
    transcriptCount: 21372,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-leptinotarsa",
    commonName: "Colorado potato beetle",
    scientificName: "Leptinotarsa decemlineata",
    taxid: 7539,
    transcriptCount: 18904,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-diabrotica",
    commonName: "Western corn rootworm",
    scientificName: "Diabrotica virgifera",
    taxid: 50390,
    transcriptCount: 19662,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-spodoptera",
    commonName: "Fall armyworm",
    scientificName: "Spodoptera frugiperda",
    taxid: 7108,
    transcriptCount: 23210,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-plutella",
    commonName: "Diamondback moth",
    scientificName: "Plutella xylostella",
    taxid: 51655,
    transcriptCount: 18540,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-bemisia",
    commonName: "Silverleaf whitefly",
    scientificName: "Bemisia tabaci",
    taxid: 7038,
    transcriptCount: 20117,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-myzus",
    commonName: "Green peach aphid",
    scientificName: "Myzus persicae",
    taxid: 13164,
    transcriptCount: 17836,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
  {
    id: "org-halyomorpha",
    commonName: "Brown marmorated stink bug",
    scientificName: "Halyomorpha halys",
    taxid: 286706,
    transcriptCount: 19348,
    hasReferenceTranscriptome: true,
    kind: "target",
  },
];

/** Species the design must not affect. Two of them deliberately have no
 * reference transcriptome: a panel where everything is screenable hides the
 * most important limitation of the whole step. */
export const NON_TARGET_ORGANISMS: Organism[] = [
  {
    id: "org-apis",
    commonName: "Western honey bee",
    scientificName: "Apis mellifera",
    taxid: 7460,
    transcriptCount: 24385,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-bombus",
    commonName: "Buff-tailed bumblebee",
    scientificName: "Bombus terrestris",
    taxid: 30195,
    transcriptCount: 20411,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-osmia",
    commonName: "Red mason bee",
    scientificName: "Osmia bicornis",
    taxid: 1437191,
    transcriptCount: 0,
    hasReferenceTranscriptome: false,
    kind: "non-target",
  },
  {
    id: "org-monarch",
    commonName: "Monarch butterfly",
    scientificName: "Danaus plexippus",
    taxid: 13037,
    transcriptCount: 16324,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-bombyx",
    commonName: "Domestic silkworm",
    scientificName: "Bombyx mori",
    taxid: 7091,
    transcriptCount: 22987,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-coccinella",
    commonName: "Seven-spot ladybird",
    scientificName: "Coccinella septempunctata",
    taxid: 41139,
    transcriptCount: 15982,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-chrysoperla",
    commonName: "Green lacewing",
    scientificName: "Chrysoperla carnea",
    taxid: 189513,
    transcriptCount: 0,
    hasReferenceTranscriptome: false,
    kind: "non-target",
  },
  {
    id: "org-nasonia",
    commonName: "Jewel wasp",
    scientificName: "Nasonia vitripennis",
    taxid: 7425,
    transcriptCount: 16891,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-tribolium",
    commonName: "Red flour beetle",
    scientificName: "Tribolium castaneum",
    taxid: 7070,
    transcriptCount: 17395,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
  {
    id: "org-daphnia",
    commonName: "Water flea",
    scientificName: "Daphnia magna",
    taxid: 35525,
    transcriptCount: 14762,
    hasReferenceTranscriptome: true,
    kind: "non-target",
  },
];

export const HUMAN_ORGANISM: Organism = {
  id: "org-human",
  commonName: "Human",
  scientificName: "Homo sapiens",
  taxid: 9606,
  transcriptCount: 172699,
  hasReferenceTranscriptome: true,
  kind: "human",
};

export const ORGANISMS: Organism[] = [
  ...TARGET_ORGANISMS,
  ...NON_TARGET_ORGANISMS,
  HUMAN_ORGANISM,
];

export function getOrganism(id: string): Organism | undefined {
  return ORGANISMS.find((one) => one.id === id);
}

/** Everything offerable in the safety panel: never a pest, always the others. */
export const SCREENABLE_POOL: Organism[] = [
  ...NON_TARGET_ORGANISMS,
  HUMAN_ORGANISM,
];

/* ---------- which species are worth screening against which pest ---------- */

/* Shared habitat, shared crop system, or a trophic link (predator, parasitoid,
 * pollinator), plus a sentinel for the pest's own order. This is the step
 * Prof. Paul Lam's advice shaped: screen a justified set of representative
 * species rather than everything, because a screen against everything is one
 * nobody can defend or run. */
const PANEL_BY_ORGANISM: Record<string, string[]> = {
  "org-varroa": ["org-apis", "org-bombus", "org-osmia", "org-nasonia"],
  "org-leptinotarsa": [
    "org-coccinella",
    "org-chrysoperla",
    "org-monarch",
    "org-apis",
  ],
  "org-diabrotica": [
    "org-monarch",
    "org-apis",
    "org-bombus",
    "org-coccinella",
  ],
  "org-spodoptera": [
    "org-monarch",
    "org-bombyx",
    "org-coccinella",
    "org-chrysoperla",
  ],
  "org-plutella": [
    "org-bombyx",
    "org-monarch",
    "org-chrysoperla",
    "org-coccinella",
  ],
  "org-bemisia": [
    "org-coccinella",
    "org-chrysoperla",
    "org-nasonia",
    "org-apis",
  ],
  "org-myzus": ["org-coccinella", "org-chrysoperla", "org-nasonia", "org-apis"],
  "org-halyomorpha": [
    "org-nasonia",
    "org-coccinella",
    "org-apis",
    "org-monarch",
  ],
};

const DEFAULT_PANEL = [
  "org-apis",
  "org-bombus",
  "org-monarch",
  "org-coccinella",
];

/** The species the pipeline recommends for this pest. Human is always offered
 * separately and is never dropped from the recommendation silently. */
export function suggestedPanelFor(organismId: string | null): string[] {
  if (!organismId) return DEFAULT_PANEL;
  return PANEL_BY_ORGANISM[organismId] ?? DEFAULT_PANEL;
}

/* ---------- Dicer-2 product length per pest ---------- */

/* The duplex length the pipeline tiles at is a property of the target's own
 * RNAi machinery, so it is derived rather than dialled.
 *
 * VARROA IS THE EXCEPTION, AND DELIBERATELY SO. The canonical arthropod
 * Dicer-2 product is 21 nt, and that is what the other seven pests get. For
 * Varroa we use 24, because our own reading of 54 sample-virus units of
 * Varroa viral small RNA puts 24 nt at the top of the population under both
 * abundance and unique-sequence weighting, with 23 nt behind it. What Dicer
 * cuts and what the mite accumulates are two different questions, and for
 * designing a window it is the second one that matters. The page sets out the
 * analysis; this is the number that comes out of it, and the demo would be
 * contradicting our own result if it said 21 here. */
const LENGTH_BY_ORGANISM: Record<
  string,
  { length: SirnaLength; note: string }
> = {
  "org-varroa": {
    length: 24,
    note: "Our own small RNA analysis puts 24 nt at the top of Varroa's viral population, so windows are scored at 24 rather than the canonical 21.",
  },
  "org-leptinotarsa": {
    length: 21,
    note: "Coleopteran Dicer-2 favours 21 nt duplexes; beetles are the most RNAi-responsive insect order studied.",
  },
  "org-diabrotica": {
    length: 21,
    note: "Coleopteran Dicer-2 favours 21 nt duplexes; beetles are the most RNAi-responsive insect order studied.",
  },
  "org-spodoptera": {
    length: 22,
    note: "Lepidopteran Dicer-2 processing is less efficient; a 22 nt duplex loads more stably.",
  },
  "org-plutella": {
    length: 22,
    note: "Lepidopteran Dicer-2 processing is less efficient; a 22 nt duplex loads more stably.",
  },
  "org-bemisia": {
    length: 21,
    note: "Hemipteran Dicer-2 processing sits at the 21 nt insect default.",
  },
  "org-myzus": {
    length: 19,
    note: "Aphid RNAi response is variable; 19 nt is the better-supported duplex length.",
  },
  "org-halyomorpha": {
    length: 21,
    note: "Hemipteran Dicer-2 processing sits at the 21 nt insect default.",
  },
};

const DEFAULT_LENGTH = {
  length: 21 as SirnaLength,
  note: "No target-specific Dicer data, so the canonical 21 nt Dicer-2 product length is used.",
};

export function lengthForOrganism(organismId: string | null): {
  length: SirnaLength;
  note: string;
} {
  if (!organismId) return DEFAULT_LENGTH;
  return LENGTH_BY_ORGANISM[organismId] ?? DEFAULT_LENGTH;
}

/* ---------- target classes ---------- */

export const TARGET_CLASSES: Array<{
  id: TargetClass;
  title: string;
  description: string;
}> = [
  {
    id: "essential",
    title: "Essential gene",
    description:
      "Housekeeping and viability targets. Knockdown kills the individual.",
  },
  {
    id: "population-control",
    title: "Fertility and germline",
    description:
      "Suppresses the population over generations rather than killing the individual.",
  },
  {
    id: "developmental",
    title: "Moulting and development",
    description:
      "Disrupts development rather than an adult-stage process.",
  },
];

/* ---------- gene name pools ---------- */

/* Named after real gene families so a ranked list reads like a screen. None of
 * these is our target, and the ranking a run produces is generated, not
 * computed from any expression or interaction dataset. */

export const ESSENTIAL_GENE_NAMES = [
  "V-ATPase subunit B",
  "Proteasome subunit PSMD4",
  "Elongation factor 1-alpha",
  "Beta-tubulin",
  "Actin-5C",
  "Heat shock protein 70",
  "COPB2 coatomer subunit",
  "Ribosomal protein S6",
  "ATP synthase subunit 6",
];

export const HOUSEKEEPING_GENE_NAMES = [
  "GAPDH",
  "Alpha-tubulin",
  "RPL32",
  "RPS18",
  "Cytochrome c oxidase I",
  "NADH dehydrogenase subunit 1",
  "Hexokinase",
  "Calmodulin",
  "Ubiquitin-conjugating enzyme",
  "Profilin",
  "Arginine kinase",
  "Odorant receptor co-receptor",
];

export const POPULATION_CONTROL_GENE_NAMES = [
  "Vitellogenin",
  "Vasa homolog",
  "Boule",
  "Piwi-like protein 1",
  "Nanos homolog",
  "Transformer-2",
  "Doublesex",
  "Oskar homolog",
  "Egalitarian",
  "Bicaudal-D",
];

export const DEVELOPMENTAL_GENE_NAMES = [
  "Ecdysone receptor",
  "Juvenile hormone esterase",
  "Chitin synthase 1",
  "Chitinase-like protein 2",
  "Broad-Complex core protein",
  "Hormone receptor 3",
  "Ultraspiracle",
  "Cuticle protein 19",
  "E93 transcription factor",
];

/* ---------- chassis, promoters, markers ---------- */

export const CHASSIS_LABELS: Record<DeliveryChassis, string> = {
  "s-cerevisiae": "S. cerevisiae",
  "ecoli-ht115": "E. coli HT115",
  "snodgrassella-alvi": "S. alvi",
};

export const CHASSIS_NOTES: Record<DeliveryChassis, string> = {
  "s-cerevisiae":
    "Our production chassis. Heat-inactivated yeast in a pollen patty is what NECTAR actually delivers.",
  "ecoli-ht115":
    "RNase III deficient, so dsRNA survives. The standard laboratory production host, and our comparison.",
  "snodgrassella-alvi":
    "A bee gut symbiont. The route we started on and abandoned on regulatory advice.",
};

export const CHASSIS_ORDER: DeliveryChassis[] = [
  "s-cerevisiae",
  "ecoli-ht115",
  "snodgrassella-alvi",
];

export interface PromoterSpec {
  id: string;
  label: string;
  terminatorLabel: string;
}

export const PROMOTERS_BY_CHASSIS: Record<DeliveryChassis, PromoterSpec[]> = {
  "s-cerevisiae": [
    { id: "gal1", label: "GAL1 promoter", terminatorLabel: "CYC1 terminator" },
    { id: "tef1", label: "TEF1 promoter", terminatorLabel: "TEF1 terminator" },
    { id: "adh1", label: "ADH1 promoter", terminatorLabel: "ADH1 terminator" },
  ],
  "ecoli-ht115": [
    { id: "t7", label: "T7 promoter", terminatorLabel: "T7 terminator" },
    { id: "t7lac", label: "T7lac promoter", terminatorLabel: "T7 terminator" },
  ],
  "snodgrassella-alvi": [
    { id: "ptrc", label: "Ptrc promoter", terminatorLabel: "rrnB T1 terminator" },
    { id: "plac", label: "Plac promoter", terminatorLabel: "rrnB T1 terminator" },
    {
      id: "prrnb",
      label: "PrrnB promoter",
      terminatorLabel: "rrnB T1 terminator",
    },
  ],
};

export interface MarkerSpec {
  id: string;
  label: string;
}

export const MARKERS_BY_CHASSIS: Record<DeliveryChassis, MarkerSpec[]> = {
  "s-cerevisiae": [
    { id: "ura3", label: "URA3" },
    { id: "leu2", label: "LEU2" },
    { id: "his3", label: "HIS3" },
    { id: "kanmx", label: "KanMX (G418R)" },
  ],
  "ecoli-ht115": [
    { id: "ampr", label: "AmpR (bla)" },
    { id: "kanr", label: "KanR (aph)" },
    { id: "cmr", label: "CmR (cat)" },
  ],
  "snodgrassella-alvi": [
    { id: "specr", label: "SpecR (aadA)" },
    { id: "kanr", label: "KanR (aph)" },
  ],
};

/** Chassis where the construct integrates into the host chromosome rather than
 * replicating as a plasmid, so it carries flanking homology arms. */
export const HOMOLOGY_ARM_CHASSIS = new Set<DeliveryChassis>([
  "s-cerevisiae",
  "snodgrassella-alvi",
]);

export function defaultPromoterId(chassis: DeliveryChassis): string {
  return PROMOTERS_BY_CHASSIS[chassis][0].id;
}

export function defaultMarkerId(chassis: DeliveryChassis): string {
  return MARKERS_BY_CHASSIS[chassis][0].id;
}

/* ---------- construct topology ---------- */

export type CassetteTopology = "dumbbell" | "hairpin" | "dual-promoter";

export const TOPOLOGIES: Array<{
  id: CassetteTopology;
  label: string;
  note: string;
}> = [
  {
    id: "dumbbell",
    label: "Loop-ended dumbbell",
    note: "Covalently closed at both ends, no promoter. This is NECTAR's own architecture.",
  },
  {
    id: "hairpin",
    label: "Single promoter, hairpin",
    note: "One promoter and a self-annealing loop. The compact shRNA cassette.",
  },
  {
    id: "dual-promoter",
    label: "Dual opposing promoters",
    note: "Both strands transcribed separately. The classic L4440 arrangement.",
  },
];
